# Utiliser l'image officielle de Nginx
FROM nginx:alpine

# Copier les fichiers du frontend dans le répertoire public de Nginx
COPY ./app/frontend /usr/share/nginx/html

# Exposer le port 80 pour permettre l'accès à Nginx
EXPOSE 80
